security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CUSTOMER: ROLE_USER
        ROLE_ADMIN: ROLE_CUSTOMER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin_secured_area:
            pattern: /administrador/.*
            provider: fos_userbundle
            anonymous: ~
            form_login:
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: /administrador/login_check
                login_path: /administrador/login
            logout:
                path:   /administrador/logout
                target: /
        members_secured_area:
            pattern: /clientes/.*
            provider: fos_userbundle
            anonymous: ~
            form_login:
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: /clientes/login_check
                login_path: /clientes/login
            logout:
                path:   /clientes/logout
                target: /
    #    main:
    #        pattern: ^/
    #        form_login:
    #            provider: fos_userbundle
    #            csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
    #            check_path: /login_check
    #            login_path: /

    #        logout:       
    #            path:   /logout
    #            target: /
    #        anonymous:    true

    access_control:
        - { path: ^/clientes/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrador/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /clientess/recover-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrador/$, role: ROLE_ADMIN }
        - { path: ^/clientes/.*, role: ROLE_CUSTOMER }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }