<?php
namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaceBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository {

    /**
     * 
     * @param int $id_documnet
     * @param int $id_user
     * @return object
     */
    public function getDataByDocumenteAndUser($id_documnet, $id_user){
       
        $q = $this->createQueryBuilder('d')
             ->leftJoin('d.users', 'u')
             ->where('u.id = :id_user')
             ->andWhere('d.id = :id_document')
             ->setParameters('id_user', $id_user)
             ->setParameter('id_document', $id_documnet) ;
                
        return $q->getQuery()->getResult();         
    }
}